fix could not find ESRGAN4X problem
mix1009/sdwebuiapi pull request #127
Opened 2023-09-18 03:19 UTC by wangzijian1010

the name of ESRGAN4X method has chaned in WEBUI, need update the name of webuiapi's name of ESRGAN

2023-11-30 16:10 UTC, davidmartinrius commented
Hi! How are you doing?

Why did you delete the lines of the function "util_get_current_model" from 779 to 785?

I see you finally return "return self.get_options()["sd_model_checkpoint"]"

Thanks,

David Martin Rius

2023-12-04 08:37 UTC, wangzijian1010 commented
> Hi! How are you doing?
> 
> Why did you delete the lines of the function "util_get_current_model" from 779 to 785?
> 
> I see you finally return "return self.get_options()["sd_model_checkpoint"]"
> 
> Thanks,
> 
> David Martin Rius

hi there, it's my mistake, i forget to undo this delte

2023-12-04 10:30 UTC, davidmartinrius commented
ok @wangzijian1010 , anyway, there is an endpoint to list the available upscalers in /sdapi/v1/upscalers

Also there is an already implemented function for that get_upscalers()

So, the hardcoded upscalers need to dissapear and this pull request is not needed anymore.

Thank you!

David Martin Rius

2023-12-05 10:50 UTC, davidmartinrius commented
Well, after reviewing it again it makes sense to have that properties hardcoded in webuiapi.py. Although they can become obsolete at any time. It's good to have them available. And if one stops working it is always possible to call the get_upscalers endpoint and update the list by hand.

If you restore the function util_get_current_model I can add my review to this pull request.

Thank you!

2023-12-06 06:56 UTC, wangzijian1010 commented
> Well, after reviewing it again it makes sense to have that properties hardcoded in webuiapi.py. Although they can become obsolete at any time. It's good to have them available. And if one stops working it is always possible to call the get_upscalers endpoint and update the list by hand.
> 
> If you restore the function util_get_current_model I can add my review to this pull request.
> 
> Thank you!

hi there!, thank you david, I have restore line 779 to 785 and you can add your review to this pull request, thanks for your reminder, i see your github repo has a lot of ai, can I add you on Skype?

2023-12-06 16:34 UTC, davidmartinrius requested changes
Remove extra line in function util_get_current_model(self)

2023-12-06 16:34 UTC, davidmartinrius commented on webuiapi/webuiapi.py
> +        return self.get_options()["sd_model_checkpoint"]
I think this line should not be here

2023-12-07 01:32 UTC, wangzijian1010 commented on webuiapi/webuiapi.py
> +        return self.get_options()["sd_model_checkpoint"]
ok i forgot it,

2023-12-07 11:11 UTC, davidmartinrius commented
> > Well, after reviewing it again it makes sense to have that properties hardcoded in webuiapi.py. Although they can become obsolete at any time. It's good to have them available. And if one stops working it is always possible to call the get_upscalers endpoint and update the list by hand.
> > If you restore the function util_get_current_model I can add my review to this pull request.
> > Thank you!
> 
> hi there!, thank you david, I have restore line 779 to 785 and you can add your review to this pull request, thanks for your reminder, i see your github repo has a lot of ai, can I add you on Skype?

Absolutely, if you wanted you can share your skype id and I will add you in my contact list. 

David Martin Rius

2023-12-11 04:52 UTC, mix1009 approved these changes

2023-12-11 04:52 UTC, merged